{
 "title": "TP1",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Response Time (server-side)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "stats.timers.response.exchange_post_response_time.mean"
    },
    {
     "target": "stats.timers.response.exchange_post_response_time.mean_90"
    },
    {
     "target": "stats.timers.response.exchange_post_response_time.lower"
    },
    {
     "target": "stats.timers.response.exchange_post_response_time.upper"
    },
    {
     "target": "stats.timers.response.exchange_post_response_time.median"
    }
   ]
  },
  {
   "title": "Volumen Total por Moneda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    { "target": "stats.volumen.total.USD" },
    { "target": "stats.volumen.total.ARS" },
    { "target": "stats.volumen.total.EUR" },
    { "target": "stats.volumen.total.BRL" }
   ]
  },
  {
   "title": "Volumen Neto por Moneda",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    { "target": "stats.gauges.volumen.neto.USD" },
    { "target": "stats.gauges.volumen.neto.ARS" },
    { "target": "stats.gauges.volumen.neto.EUR" },
    { "target": "stats.gauges.volumen.neto.BRL" }
   ]
  }
 ]
}