{
 "title": "Business Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Volumen total vs neto ARS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "integral(stats.arvault.volumen.total.ARS)"
    },
    {
     "target": "integral(stats.arvault.volumen.neto.ARS)"
    }
   ]
  },
  {
   "title": "Volumen total vs neto USD",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "target": "integral(stats.arvault.volumen.total.USD)"
    },
    {
     "target": "integral(stats.arvault.volumen.neto.USD)"
    }
   ]
  },
  {
   "title": "Volumen total vs neto EUR",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "target": "integral(stats.arvault.volumen.total.EUR)"
    },
    {
     "target": "integral(stats.arvault.volumen.neto.EUR)"
    }
   ]
  },
  {
   "title": "Volumen total vs neto BRL",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "target": "integral(stats.arvault.volumen.total.BRL)"
    },
    {
     "target": "integral(stats.arvault.volumen.neto.BRL)"
    }
   ]
  },
  {
   "title": "Volumen total vs neto BRL",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "integral(stats.arvault.volumen.total.USD\n)"
    },
    {
     "target": "integral(stats.arvault.volumen.total.BRL)"
    },
    {
     "target": "integral(stats.arvault.volumen.total.EUR)"
    }
   ]
  }
 ]
}